# Generated by Django 3.1.3 on 2020-12-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport_ocr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportimage',
            name='name',
        ),
    ]
