# Generated by Django 3.1.3 on 2020-12-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_ocr', '0002_remove_passportimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportimage',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
