# Generated by Django 3.1.3 on 2021-01-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_ocr', '0003_passportimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_type', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PassportImage',
        ),
    ]
